spring:
  datasource:
    url: jdbc:mysql://localhost:3306/last_project_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  error:
    include-stacktrace: never